# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [3]:
l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [4]:
mat= [[1,2,3],[4,5,6],[7,8,9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [5]:
np.arange(1,18,2).reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [9]:
np.random.randint(0,10,10)

array([0, 0, 7, 2, 8, 2, 5, 2, 3, 2])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [10]:
l=np.array([1,2,3,4,5])
l.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [11]:
l.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [12]:
list1=np.array([1,2,3,4,5,6,7,8,9,10])
print(list1[2])
print(list1[3])
print(list1[-2])

3
4
9


Print alternate elements of that array

In [13]:
list1[0:len(list1):2]

array([1, 3, 5, 7, 9])

Change last 3 elements into 100 using broadcasting and print

In [16]:
list1[7:10]=100
list1

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [21]:
mat=np.random.randint(0,50,25).reshape(5,5)
mat

array([[31, 45,  1, 47, 40],
       [31, 18, 44, 16, 34],
       [31, 20, 43,  7,  7],
       [22, 10,  1,  4, 10],
       [29, 21, 48, 12, 39]])

In [22]:
mat[1:4,1:4]

array([[18, 44, 16],
       [20, 43,  7],
       [10,  1,  4]])